name: NDC News Automation

on:
  push:
    paths:
      - 'data/*.pdf' # 偵測 data 資料夾內的 PDF 上傳

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pdfplumber

      - name: Run Analysis Script
        run: python main.py

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_filename: index.html
